# Generated by Django 5.1 on 2024-08-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=100)),
                ('qunatity', models.IntegerField()),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('powerRating', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MechanicalPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=100)),
                ('qunatity', models.IntegerField()),
                ('material', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=100)),
                ('qunatity', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('purity', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
